version: "3"

tasks:
  fmt:
    cmds:
      - nix fmt

  statix-check:
    cmds:
      - nix develop -c statix check -i machines/cml-jpr-net/vpsadminos.nix machines/atlas/hardware-configuration.nix

  dry-build-atlas:
    deps:
      - task: dry-build
        vars: { SYSTEM: atlas }

  dry-build-wheatley:
    deps:
      - task: dry-build
        vars: { SYSTEM: wheatley }

  dry-build:
    cmds:
      - nix build --dry-run .#nixosConfigurations.{{.SYSTEM}}.config.system.build.toplevel -L
    prefix: build-{{.SYSTEM}}
