version: '3'

tasks:
  fmt:
    cmds:
      - nix fmt

  statix-check:
    cmds:
      - nix develop -c statix check -i machines/cml-jpr-net/vpsadminos.nix machines/atlas/hardware-configuration.nix

  dry-build-machines:
    cmds:
      - nix build --dry-run .#nixosConfigurations.atlas.config.system.build.toplevel -L
      - nix build --dry-run .#nixosConfigurations.wheatley.config.system.build.toplevel -L
      - nix build --dry-run .#nixosConfigurations.vpsfree.config.system.build.toplevel -L
      - nix build --dry-run .#nixosConfigurations.home-hub.config.system.build.toplevel -L