version: "3"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  nix:fmt:
    desc: Format all .nix files with nixfmt
    cmds:
      - find . -type f -name "*.nix" -print0 | xargs -0 nixfmt

  nix:statix:
    desc: Run statix static analysis on NixOS configurations
    cmds:
      - nix develop -c statix check -i machines/cml-jpr-net/vpsadminos.nix machines/hetz01/hardware-configuration.nix

  build:hetz01:
    desc: Dry-run build for the hetz01 NixOS configuration
    deps:
      - task: build:dry
        vars: { SYSTEM: hetz01 }

  build:wheatley:
    desc: Dry-run build for the Wheatley NixOS configuration
    deps:
      - task: build:dry
        vars: { SYSTEM: wheatley }

  build:dry:
    desc: Dry-run build for a given NixOS system (SYSTEM=<name>)
    cmds:
      - nix build --dry-run .#nixosConfigurations.{{.SYSTEM}}.config.system.build.toplevel -L
    prefix: build-{{.SYSTEM}}
