# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "virtio_scsi"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.loader.grub.enable = true;
  boot.loader.grub.devices = [ "/dev/sda" ];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/iso" = {
    device = "/dev/disk/by-uuid/1980-01-01-00-00-00-00";
    fsType = "iso9660";
  };

  fileSystems."/nix/.ro-store" = {
    device = "/iso/nix-store.squashfs";
    fsType = "squashfs";
    options = [ "loop" ];
  };

  fileSystems."/nix/.rw-store" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/nix/store" = {
    device = "overlay";
    fsType = "overlay";
  };

  fileSystems."/mnt" = {
    device = "/dev/disk/by-uuid/5b9da607-94fd-46f1-812d-c25254654018";
    fsType = "ext4";
  };

  fileSystems."/mnt/boot" = {
    device = "/dev/disk/by-uuid/9abfd5b8-bf6a-4425-8211-149c20bf5871";
    fsType = "ext4";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/98415ca5-fca7-4f00-af21-5fe1f0f4a2ff"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
