theme="jetbrains_dark"

[editor.auto-save]
focus-lost = true            # save when Helix loses focus
after-delay.enable = true    # save after a delay
after-delay.timeout = 3000   # delay in ms (3s here)
