name: "Nix fmt"
on:
  pull_request:
  push:
jobs:
  nix_fmt:
    runs-on: [ ubuntu-24.04 ]
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop -c task nix-fmt
    - uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        author_name: GitHub Actions
        author_email: jacfal.tech@protonmail.com
        message: "Github Actions: Nix fmt"