name: "Periodic flake update"
on:
  workflow_dispatch:
  schedule:
    # schedule: At 01:00 on Monday
    - cron:  '0 1 * * 1'
jobs:
  flake_update:
    runs-on: [ ubuntu-24.04 ]
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake update
    - uses: EndBug/add-and-commit@v9
      with:
        add: 'flake.lock'
        author_name: GitHub Actions
        author_email: jacfal.tech@protonmail.com
        message: "Github Actions: Update flake.lock"